//
//  PackageListingInteractor.swift
//  Enrich_TMA
//
//  Created by Harshal on 06/03/20.
//  Copyright (c) 2020 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PackageListingBusinessLogic {
    func doGetOffersValuePackages()
}

protocol PackageListingDataStore {
  //var name: String { get set }
}

class PackageListingInteractor: PackageListingBusinessLogic, PackageListingDataStore {
  var presenter: PackageListingPresentationLogic?
  var worker: PackageListingWorker?
  //var name: String = ""

  // MARK: Do something

  func doGetOffersValuePackages() {
      worker = PackageListingWorker()
      worker?.presenter = presenter
      worker?.getOfferValuePackages()
  }
}
