//
//  PackageListingModels.swift
//  Enrich_TMA
//
//  Created by Harshal on 06/03/20.
//  Copyright (c) 2020 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum PackageListing {
    // MARK: Use cases

    enum OffersValuePackages {
        struct Response: Codable {
            let status: Bool?
            let message: String?
            let data: DateResponse?
        }
        struct DateResponse: Codable {
            let package_list: [Package_listValues]?
        }

        struct Package_listValues: Codable {
            let id: String?
            let name: String?
            let image: String?
            let swatch_image: String?
            let short_description: String?
            let description: String?
            let sku: String?
            //let add-to-url : String?
            let validity: Int?
            let salon_data: [ApplyCouponModel.GetCoupons.SalonData]?
            let salon_list: String?
            let price: String?
            let price_cma: Double?
            let offer_price: String?
            let offer_price_cma: Double?
            let type: Int?
            let package_type: String?
            let data: [ServicePackageIncludes]?
            let package_type_cma: Int?
        }

        struct SalonData: Codable {
            let salon_id: String?
            let salon_code: String?
            let salon_name: String?
        }

        struct ServicePackageIncludes: Codable {
            let qty: String?
            let name: String?
        }

    }
}
