//
//  InvoiceInteractor.swift
//  Enrich_TMA
//
//  Created by Harshal Patil on 12/11/19.
//  Copyright (c) 2019 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol InvoiceBusinessLogic {
    func doGetInvoiceDetails(accessToken: String, request: Invoice.GetInvoiceDetails.Request)
    func doPostUpdateAppointmentStatus(appointmentId: String, request: JobCard.ChangeAppointmentStatus.Request)
    func getCustomerWalletRewardPointAndPackages(customerId: String, quoteId: String)
}

class InvoiceInteractor: InvoiceBusinessLogic {
    var presenter: InvoicePresentationLogic?
    var worker: InvoiceWorker?
    //var name: String = ""

    // MARK: Do something

    func doGetInvoiceDetails(accessToken: String, request: Invoice.GetInvoiceDetails.Request) {
        worker = InvoiceWorker()
        worker?.presenter = self.presenter
        worker?.getRequestForInvoiceDetails(accessToken: accessToken, request: request)
    }

    func doPostUpdateAppointmentStatus(appointmentId: String, request: JobCard.ChangeAppointmentStatus.Request) {
        worker = InvoiceWorker()
        worker?.presenter = self.presenter
        worker?.postRequestForChangeAppointmentStatus(appointmentId: appointmentId, request: request)
    }

    func getCustomerWalletRewardPointAndPackages(customerId: String, quoteId: String) {
        worker = InvoiceWorker()
        worker?.presenter = self.presenter
        worker?.getCustomerWalletRewardPointAndPackages(customerId: customerId, quoteId: quoteId)
    }

}
