//
//  AddNewPettyCashInteractor.swift
//  Enrich_TMA
//
//  Created by Harshal on 01/04/20.
//  Copyright (c) 2020 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AddNewPettyCashBusinessLogic {
    func doPostPettyCashEntryRequest(request: AddNewPettyCash.AddEntry.Request, method: HTTPMethod)
}

class AddNewPettyCashInteractor: AddNewPettyCashBusinessLogic {
    var presenter: AddNewPettyCashPresentationLogic?
    var worker: AddNewPettyCashWorker?
    //var name: String = ""

    // MARK: Do something

    func doPostPettyCashEntryRequest(request: AddNewPettyCash.AddEntry.Request, method: HTTPMethod) {
        worker = AddNewPettyCashWorker()
        worker?.presenter = self.presenter
        worker?.addNewPettyCashEntry(request: request, method: method)
    }
}
