//
//  AddNewPettyCashModels.swift
//  Enrich_TMA
//
//  Created by Harshal on 01/04/20.
//  Copyright (c) 2020 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum AddNewPettyCash {
    // MARK: Use cases

    enum AddEntry {

        struct Request: Codable {
            let salon_id: String
            let technician_id: String
            let amount: String
            let is_custom: Bool
            let action: Int
            let technician_name: String
            let purpose: String
            let attachment: String
        }

        struct Response: Codable {
            var status: Bool = false
            var message: String = ""
        }
    }
}
