//
//  PettyCashListingWorker.swift
//  Enrich_TMA
//
//  Created by Harshal Patil on 27/11/19.
//  Copyright (c) 2019 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class PettyCashListingWorker {

    let networkLayer = NetworkLayerAlamofire() // Uncomment this in case do request using Alamofire for client request
    // let networkLayer = NetworkLayer() // Uncomment this in case do request using URLsession
    var presenter: PettyCashListingPresentationLogic?

    func getRequestForCheckInStatus(request: PettyCashListing.GetHistory.Request, method: HTTPMethod) {
        // *********** NETWORK CONNECTION

        let errorHandler: (String) -> Void = { (error) in
            print(error)
            self.presenter?.presentError(responseError: error)
        }
        let successHandler: (PettyCashListing.GetHistory.Response) -> Void = { (response) in
            self.presenter?.presentSuccess(response: response)
        }

        let url = ConstantAPINames.getPettyCashHistory.rawValue + "&salon_id=\(request.salon_id)" + "&technician_id=\(request.technician_id)"

        self.networkLayer.get(urlString: url, headers: ["Authorization": "Bearer \(GenericClass.sharedInstance.isuserLoggedIn().accessToken)"], successHandler: successHandler, errorHandler: errorHandler)
    }

}
