//
//  ViewCTCPresenter.swift
//  Enrich_TMA
//
//  Created by Harshal on 21/12/21.
//  Copyright (c) 2021 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ViewCTCPresentationLogic
{
//  func presentSomething(response: ViewCTC.Something.Response)
    func presentSuccessCTC<T: Decodable>(response: T)
    func presentErrorCTC(responseError: String?)
}

class ViewCTCPresenter: ViewCTCPresentationLogic
{
  weak var viewController: ViewCTCDisplayLogic?
  
  // MARK: Do something
  
//  func presentSomething(response: ViewCTC.Something.Response)
//  {
//    let viewModel = ViewCTC.Something.ViewModel()
//    viewController?.displaySomething(viewModel: viewModel)
//  }
    
    func presentSuccessCTC<T>(response: T) where T: Decodable {
        viewController?.displaySuccessCTC(viewModel: response)
    }

    func presentErrorCTC(responseError: String?) {
        viewController?.displayErrorCTC(errorMessage: responseError)
    }
}
