//
//  IncentiveInteractor.swift
//  Enrich_TMA
//
//  Created by Harshal on 21/12/21.
//  Copyright (c) 2021 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol IncentiveBusinessLogic
{
  func doSomething(request: Incentive.Something.Request)
}

protocol IncentiveDataStore
{
  //var name: String { get set }
}

class IncentiveInteractor: IncentiveBusinessLogic, IncentiveDataStore
{
  var presenter: IncentivePresentationLogic?
  var worker: IncentiveWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Incentive.Something.Request)
  {
    worker = IncentiveWorker()
    worker?.doSomeWork()
    
    let response = Incentive.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
