//
//  RateTheCustomerViewController.swift
//  Enrich_TMA
//
//  Created by Harshal Patil on 16/10/19.
//  Copyright (c) 2019 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Cosmos

protocol RateTheCustomerDisplayLogic: class
{
    func displaySomething(viewModel: RateTheCustomer.Something.ViewModel)
}

class RateTheCustomerVC: UIViewController, RateTheCustomerDisplayLogic
{
    var interactor: RateTheCustomerBusinessLogic?
    
    @IBOutlet weak private var btnSubmit: UIButton!
    @IBOutlet weak private var ratingsView: CosmosView!
    @IBOutlet weak private var txtfAddComment: UITextField!
    @IBOutlet weak private var txtfSuggestion: UITextField!
    
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
    {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder)
    {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = RateTheCustomerInteractor()
        let presenter = RateTheCustomerPresenter()
        viewController.interactor = interactor
        interactor.presenter = presenter
        presenter.viewController = viewController
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        //            if let scene = segue.identifier {
        //                let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
        //                if let router = router, router.responds(to: selector) {
        //                    router.perform(selector, with: segue)
        //                }
        //            }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        doSomething()
    }
    
    // MARK: Do something
    
    //@IBOutlet weak var nameTextField: UITextField!
    
    func doSomething()
    {
        let request = RateTheCustomer.Something.Request()
        interactor?.doSomething(request: request)
    }
    
    func displaySomething(viewModel: RateTheCustomer.Something.ViewModel)
    {
        //nameTextField.text = viewModel.name
    }
    
    @IBAction func actionSubmit(_ sender: UIButton) {
    }
    
}
