//
//  NotificationsModels.swift
//  Enrich_TMA
//
//  Created by Harshal Patil on 09/10/19.
//  Copyright (c) 2019 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Notifications {
  // MARK: Use cases

    enum MyNotificationList {
        struct Response: Codable {
            let status: Bool?
            let data: [MyNotificationListItems]?
            let message: String?
        }
        struct MyNotificationListItems: Codable {
            let notification_id: String?
            let type: String?
            let device_id: String?
            let customer_id: String?
            let message: String?
            let module: String?
            let category: String?
            let is_active: String?
            let status: String?
            let created_at: String?
            let updated_at: String?
            let subject: String?
        }

    }
}
