//
//  ChangeTimeSlotPresenter.swift
//  Enrich_TMA
//
//  Created by Harshal on 14/04/20.
//  Copyright (c) 2020 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChangeTimeSlotPresentationLogic {
    func presentSuccess<T: Decodable>(response: T)
    func presentError(responseError: String?)
}

class ChangeTimeSlotPresenter: ChangeTimeSlotPresentationLogic {
    weak var viewController: ChangeTimeSlotDisplayLogic?

    // MARK: Do something

    func presentSuccess<T: Decodable>(response: T) {
        viewController?.displaySuccess(viewModel: response)
    }

    func presentError(responseError: String?) {
        viewController?.displayError(errorMessage: responseError)
    }
}
