//
//  ChangeTimeSlotInteractor.swift
//  Enrich_TMA
//
//  Created by Harshal on 14/04/20.
//  Copyright (c) 2020 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChangeTimeSlotBusinessLogic {
    func doPostAddBlankAppointment(request: ChangeTimeSlot.AddBlank.Request)
    func doPostAddMultipleServices(request: ChangeTimeSlot.AddMultipleServices.Request)
    func doPostChangeServiceTimeslot(request: ModifyAppointment.ChangeTimeslot.Request, method: HTTPMethod)
    func doPostChangeAppointmentTimeslot(request: ModifyAppointment.ChangeTimeslot.Request, method: HTTPMethod)
}

class ChangeTimeSlotInteractor: ChangeTimeSlotBusinessLogic {
    var presenter: ChangeTimeSlotPresentationLogic?
    var worker: ChangeTimeSlotWorker?
    //var name: String = ""

    // MARK: Do something

    func doPostAddBlankAppointment(request: ChangeTimeSlot.AddBlank.Request) {
        worker = ChangeTimeSlotWorker()
        worker?.presenter = presenter
        worker?.postRequestCreateBlankAppointment(request: request)
    }

    func doPostAddMultipleServices(request: ChangeTimeSlot.AddMultipleServices.Request) {
        worker = ChangeTimeSlotWorker()
        worker?.presenter = presenter
        worker?.postRequestAddServices(request: request)
    }

    func doPostChangeServiceTimeslot(request: ModifyAppointment.ChangeTimeslot.Request, method: HTTPMethod) {
        worker = ChangeTimeSlotWorker()
        worker?.presenter = self.presenter
        worker?.postRequestForChangeServiceTimeslot(request: request, method: method)
    }

    func doPostChangeAppointmentTimeslot(request: ModifyAppointment.ChangeTimeslot.Request, method: HTTPMethod) {
        worker = ChangeTimeSlotWorker()
        worker?.presenter = self.presenter
        worker?.postRequestForChangeAppointmentTimeslot(request: request, method: method)
    }

}
