//
//  DateFilterPresenter.swift
//  Enrich_TMA
//
//  Created by Harshal on 16/08/21.
//  Copyright (c) 2021 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DateFilterPresentationLogic
{
  func presentSomething(response: DateFilter.Something.Response)
}

class DateFilterPresenter: DateFilterPresentationLogic
{
  weak var viewController: DateFilterDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: DateFilter.Something.Response)
  {
    let viewModel = DateFilter.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
