# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Enrich_TMA' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Enrich_TMA

    pod 'Alamofire'
    pod 'Kingfisher', '~> 4.0'
    pod 'Firebase/Core'
    pod 'Fabric', '~> 1.9.0'
    pod 'Crashlytics', '~> 3.12.0'
    pod 'Cosmos'
    pod 'GooglePlaces', '= 3.0.3'

  target 'Enrich_TMATests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Enrich_TMAUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
