# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Enrich_TMA' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Enrich_TMA

    pod 'Alamofire'
    pod 'Kingfisher', '~> 4.0'
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
    pod 'Firebase/Crashlytics'
    pod 'Cosmos'
    pod 'TagListView', '~> 1.0'
    pod 'SwiftLint'
    pod 'Charts'
    pod 'FSCalendar'

  target 'Enrich_TMATests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Enrich_TMAUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
