//
//  CustomerEngagementPresenter.swift
//  Enrich_TMA
//
//  Created by Harshal on 05/08/21.
//  Copyright (c) 2021 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CustomerEngagementPresentationLogic
{
  func presentSomething(response: CustomerEngagement.Something.Response)
}

class CustomerEngagementPresenter: CustomerEngagementPresentationLogic
{
  weak var viewController: CustomerEngagementDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: CustomerEngagement.Something.Response)
  {
    let viewModel = CustomerEngagement.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
