//
//  CustomerEngagementInteractor.swift
//  Enrich_TMA
//
//  Created by Harshal on 05/08/21.
//  Copyright (c) 2021 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CustomerEngagementBusinessLogic
{
  func doSomething(request: CustomerEngagement.Something.Request)
}

protocol CustomerEngagementDataStore
{
  //var name: String { get set }
}

class CustomerEngagementInteractor: CustomerEngagementBusinessLogic, CustomerEngagementDataStore
{
  var presenter: CustomerEngagementPresentationLogic?
  var worker: CustomerEngagementWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: CustomerEngagement.Something.Request)
  {
    worker = CustomerEngagementWorker()
    worker?.doSomeWork()
    
    let response = CustomerEngagement.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
