//
//  SendPaymentLinkPresenter.swift
//  Enrich_TMA
//
//  Created by Harshal on 09/06/20.
//  Copyright (c) 2020 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SendPaymentLinkPresentationLogic {
    func presentSuccess<T: Decodable>(response: T)
    func presentError(responseError: String?)
}

class SendPaymentLinkPresenter: SendPaymentLinkPresentationLogic {
    weak var viewController: SendPaymentLinkDisplayLogic?

    // MARK: Do something

    func presentError(responseError: String?) {
        viewController?.displayError(errorMessage: responseError)
    }

    func presentSuccess<T>(response: T) where T: Decodable {
        viewController?.displaySuccess(viewModel: response)
    }
}
