//
//  PowerBIReportInteractor.swift
//  Enrich_SMA
//
//  Created by Harshal on 07/08/20.
//  Copyright (c) 2020 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PowerBIReportBusinessLogic {
    func doGetReportDetails(reportId: String)
}

class PowerBIReportInteractor: PowerBIReportBusinessLogic {
    var presenter: PowerBIReportPresentationLogic?
    var worker: PowerBIReportWorker?
    //var name: String = ""

    // MARK: Do something

    func doGetReportDetails(reportId: String) {
        worker = PowerBIReportWorker()
        worker?.presenter = self.presenter
        worker?.getReportDetails(reportId: reportId)
    }
}
