//
//  RevenuePresenter.swift
//  Enrich_TMA
//
//  Created by Harshal on 04/08/21.
//  Copyright (c) 2021 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RevenuePresentationLogic
{
  func presentSomething(response: Revenue.Something.Response)
}

class RevenuePresenter: RevenuePresentationLogic
{
  weak var viewController: RevenueDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Revenue.Something.Response)
  {
    let viewModel = Revenue.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
