//
//  EarningsPresenter.swift
//  Enrich_TMA
//
//  Created by Harshal on 13/12/21.
//  Copyright (c) 2021 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EarningsPresentationLogic
{
  func presentSomething(response: Earnings.Something.Response)
}

class EarningsPresenter: EarningsPresentationLogic
{
  weak var viewController: EarningsDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Earnings.Something.Response)
  {
    let viewModel = Earnings.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
