//
//  MyDetailsInteractor.swift
//  Enrich_TMA
//
//  Created by Harshal on 22/02/21.
//  Copyright (c) 2021 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MyDetailsBusinessLogic
{
  func doSomething(request: MyDetails.Something.Request)
}

protocol MyDetailsDataStore
{
  //var name: String { get set }
}

class MyDetailsInteractor: MyDetailsBusinessLogic, MyDetailsDataStore
{
  var presenter: MyDetailsPresentationLogic?
  var worker: MyDetailsWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: MyDetails.Something.Request)
  {
    worker = MyDetailsWorker()
    worker?.doSomeWork()
    
    let response = MyDetails.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
