//
//  AuthoriseServicesInteractor.swift
//  Enrich_TMA
//
//  Created by Harshal Patil on 07/01/20.
//  Copyright (c) 2020 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AuthoriseServicesBusinessLogic {
    func doPostServiceListData(request: MyProfile.GetServiceList.Request)
    func doPostReplaceService(request: ModifyAppointment.ReplaceService.Request, method: HTTPMethod)
    func doPostAddSingleService(request: ModifyAppointment.AddSingleService.Request, method: HTTPMethod)
}

class AuthoriseServicesInteractor: AuthoriseServicesBusinessLogic {
    var presenter: AuthoriseServicesPresentationLogic?
    var worker: AuthoriseServicesWorker?
    //var name: String = ""

    // MARK: Do something
    
    func doPostServiceListData(request: MyProfile.GetServiceList.Request) {
        worker = AuthoriseServicesWorker()
        worker?.presenter = self.presenter
        worker?.postRequestForServiceList(request: request)
    }

    func doPostReplaceService(request: ModifyAppointment.ReplaceService.Request, method: HTTPMethod) {
        worker = AuthoriseServicesWorker()
        worker?.presenter = self.presenter
        worker?.postRequestForReplaceService(request: request, method: method)
    }

    func doPostAddSingleService(request: ModifyAppointment.AddSingleService.Request, method: HTTPMethod) {
        worker = AuthoriseServicesWorker()
        worker?.presenter = self.presenter
        worker?.postRequestForAddSingleService(request: request, method: method)
    }

}
