//
//  GenericCustomerConsulationInteractor.swift
//  Enrich_TMA
//
//  Created by Harshal Patil on 04/11/19.
//  Copyright (c) 2019 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol GenericCustomerConsulationBusinessLogic
{
  func doSomething(request: GenericCustomerConsulation.Something.Request)
}

protocol GenericCustomerConsulationDataStore
{
  //var name: String { get set }
}

class GenericCustomerConsulationInteractor: GenericCustomerConsulationBusinessLogic, GenericCustomerConsulationDataStore
{
  var presenter: GenericCustomerConsulationPresentationLogic?
  var worker: GenericCustomerConsulationWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: GenericCustomerConsulation.Something.Request)
  {
    worker = GenericCustomerConsulationWorker()
    worker?.doSomeWork()
    
    let response = GenericCustomerConsulation.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
