//
//  GenericCustomerConsulationInteractor.swift
//  Enrich_TMA
//
//  Created by Harshal Patil on 04/11/19.
//  Copyright (c) 2019 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol GenericCustomerConsulationBusinessLogic {
    func doGetServiceSpcificFormData(request: GenericCustomerConsulation.FormData.Request, method: HTTPMethod)
    func doPostSpcificFormData(request: GenericCustomerConsulation.SubmitFormData.Request, method: HTTPMethod)
}

class GenericCustomerConsulationInteractor: GenericCustomerConsulationBusinessLogic {

    var presenter: GenericCustomerConsulationPresentationLogic?
    var worker: GenericCustomerConsulationWorker?
    //var name: String = ""

    // MARK: Do something

    func doGetServiceSpcificFormData(request: GenericCustomerConsulation.FormData.Request, method: HTTPMethod) {
        worker = GenericCustomerConsulationWorker()
        worker?.presenter = self.presenter
        worker?.getServiceSpecificConsultationForm(request: request, method: method)
    }

    func doPostSpcificFormData(request: GenericCustomerConsulation.SubmitFormData.Request, method: HTTPMethod) {
        worker = GenericCustomerConsulationWorker()
        worker?.presenter = self.presenter
        worker?.postSubmitSpecificConsultationForm(request: request, method: method)
    }

}
