//
//  CTCDetailsPresenter.swift
//  Enrich_TMA
//
//  Created by Harshal on 23/02/21.
//  Copyright (c) 2021 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CTCDetailsPresentationLogic
{
  func presentSomething(response: CTCDetails.Something.Response)
}

class CTCDetailsPresenter: CTCDetailsPresentationLogic
{
  weak var viewController: CTCDetailsDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: CTCDetails.Something.Response)
  {
    let viewModel = CTCDetails.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
