//
//  AwardsInteractor.swift
//  Enrich_TMA
//
//  Created by Harshal on 21/12/21.
//  Copyright (c) 2021 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AwardsBusinessLogic
{
  func doSomething(request: Awards.Something.Request)
}

protocol AwardsDataStore
{
  //var name: String { get set }
}

class AwardsInteractor: AwardsBusinessLogic, AwardsDataStore
{
  var presenter: AwardsPresentationLogic?
  var worker: AwardsWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Awards.Something.Request)
  {
    worker = AwardsWorker()
    worker?.doSomeWork()
    
    let response = Awards.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
