//
//  BillOfMaterialWorker.swift
//  Enrich_TMA
//
//  Created by Harshal Patil on 05/12/19.
//  Copyright (c) 2019 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class BillOfMaterialWorker {

    let networkLayer = NetworkLayerAlamofire() // Uncomment this in case do request using Alamofire for client request
    var presenter: BillOfMaterialPresentationLogic?

    func getBOMRelatedProducts(productCode: String) {

        let errorHandler: (String) -> Void = { (error) in
            print(error)
            self.presenter?.presentError(responseError: error)
        }
        let successHandler: (BillOfMaterial.RelatedBOMProducts.Response) -> Void = { (response) in
            print(response)
            self.presenter?.presentGetBOMRelatedProductsSuccess(response: response)
        }

        let url = ConstantAPINames.getRelatedBOMProducts.rawValue + productCode

        self.networkLayer.get(urlString: url, headers: [:], successHandler: successHandler, errorHandler: errorHandler)
    }
}
