//
//  AppointmentFilterInteractor.swift
//  Enrich_TMA
//
//  Created by Harshal Patil on 09/10/19.
//  Copyright (c) 2019 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AppointmentFilterBusinessLogic {
  func doSomething(request: AppointmentFilter.Something.Request)
}

protocol AppointmentFilterDataStore {
  //var name: String { get set }
}

class AppointmentFilterInteractor: AppointmentFilterBusinessLogic, AppointmentFilterDataStore {
  var presenter: AppointmentFilterPresentationLogic?
  var worker: AppointmentFilterWorker?
  //var name: String = ""

  // MARK: Do something

  func doSomething(request: AppointmentFilter.Something.Request) {
    worker = AppointmentFilterWorker()
    worker?.doSomeWork()

    let response = AppointmentFilter.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
