//
//  MyCustomersPresenter.swift
//  Enrich_TMA
//
//  Created by Harshal Patil on 16/10/19.
//  Copyright (c) 2019 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MyCustomersPresentationLogic
{
  func presentSomething(response: MyCustomers.Something.Response)
}

class MyCustomersPresenter: MyCustomersPresentationLogic
{
  weak var viewController: MyCustomersDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: MyCustomers.Something.Response)
  {
    let viewModel = MyCustomers.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
