//
//  MyCustomersInteractor.swift
//  Enrich_TMA
//
//  Created by Harshal Patil on 16/10/19.
//  Copyright (c) 2019 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MyCustomersBusinessLogic
{
  func doSomething(request: MyCustomers.Something.Request)
}

protocol MyCustomersDataStore
{
  //var name: String { get set }
}

class MyCustomersInteractor: MyCustomersBusinessLogic, MyCustomersDataStore
{
  var presenter: MyCustomersPresentationLogic?
  var worker: MyCustomersWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: MyCustomers.Something.Request)
  {
    worker = MyCustomersWorker()
    worker?.doSomeWork()
    
    let response = MyCustomers.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
