//
//  CustomerFeedbackInteractor.swift
//  Enrich_TMA
//
//  Created by Harshal on 05/08/21.
//  Copyright (c) 2021 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CustomerFeedbackBusinessLogic
{
  func doSomething(request: CustomerFeedback.Something.Request)
}

protocol CustomerFeedbackDataStore
{
  //var name: String { get set }
}

class CustomerFeedbackInteractor: CustomerFeedbackBusinessLogic, CustomerFeedbackDataStore
{
  var presenter: CustomerFeedbackPresentationLogic?
  var worker: CustomerFeedbackWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: CustomerFeedback.Something.Request)
  {
    worker = CustomerFeedbackWorker()
    worker?.doSomeWork()
    
    let response = CustomerFeedback.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
