//
//  SelectDependentPresenter.swift
//  Enrich_TMA
//
//  Created by Harshal on 23/11/20.
//  Copyright (c) 2020 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SelectDependentPresentationLogic
{
  func presentSomething(response: SelectDependent.Something.Response)
}

class SelectDependentPresenter: SelectDependentPresentationLogic
{
  weak var viewController: SelectDependentDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: SelectDependent.Something.Response)
  {
    let viewModel = SelectDependent.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
