//
//  RevenueInteractor.swift
//  Enrich_TMA
//
//  Created by Harshal Patil on 11/10/19.
//  Copyright (c) 2019 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RevenueBusinessLogic
{
  func doSomething(request: Revenue.Something.Request)
}

protocol RevenueDataStore
{
  //var name: String { get set }
}

class RevenueInteractor: RevenueBusinessLogic, RevenueDataStore
{
  var presenter: RevenuePresentationLogic?
  var worker: RevenueWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Revenue.Something.Request)
  {
    worker = RevenueWorker()
    worker?.doSomeWork()
    
    let response = Revenue.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
