//
//  AppointmentDetailsModels.swift
//  Enrich_TMA
//
//  Created by Harshal Patil on 09/10/19.
//  Copyright (c) 2019 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum AppointmentDetails {
  // MARK: Use cases

    enum AppointmentStatus {

        struct Response: Codable {
            var status: Bool = false
            var message: String = ""
            let data: Data?
        }

        struct Data: Codable {
            let complete: Bool
        }
    }

    enum UploadSelfie {
        struct Request: Codable {
            let appointment_id: Int64?
            let selfie_image: String?
        }

        struct Response: Codable {
            var status: Bool = false
            var message: String = ""
        }
    }
}
