//
//  AppointmentDetailsInteractor.swift
//  Enrich_TMA
//
//  Created by Harshal Patil on 09/10/19.
//  Copyright (c) 2019 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AppointmentDetailsBusinessLogic
{
  func doSomething(request: AppointmentDetails.Something.Request)
}

protocol AppointmentDetailsDataStore
{
  //var name: String { get set }
}

class AppointmentDetailsInteractor: AppointmentDetailsBusinessLogic, AppointmentDetailsDataStore
{
  var presenter: AppointmentDetailsPresentationLogic?
  var worker: AppointmentDetailsWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: AppointmentDetails.Something.Request)
  {
    worker = AppointmentDetailsWorker()
    worker?.doSomeWork()
    
    let response = AppointmentDetails.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
