//
//  EmployeeListingPresenter.swift
//  Enrich_TMA
//
//  Created by Harshal Patil on 22/10/19.
//  Copyright (c) 2019 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol EmployeeListingPresentationLogic
{
  func presentSomething(response: EmployeeListing.Something.Response)
}

class EmployeeListingPresenter: EmployeeListingPresentationLogic
{
  weak var viewController: EmployeeListingDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: EmployeeListing.Something.Response)
  {
    let viewModel = EmployeeListing.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
