//
//  EmployeeListingWorker.swift
//  Enrich_TMA
//
//  Created by Harshal Patil on 22/10/19.
//  Copyright (c) 2019 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class EmployeeListingWorker {

    let networkLayer = NetworkLayerAlamofire() // Uncomment this in case do request using Alamofire for client request
    var presenter: EmployeeListingPresentationLogic?

    func postRequestForServiceList(request: EmployeeListing.GetEmployeeList.Request, method: HTTPMethod) {

        let errorHandler: (String) -> Void = { (error) in
            print(error)
            self.presenter?.presentGetEmployeeListError(responseError: error)
        }
        let successHandler: (EmployeeListing.GetEmployeeList.Response) -> Void = { (response) in
            print(response)
            self.presenter?.presentGetEmployeeListSuccess(response: response)
        }

        self.networkLayer.post(urlString: ConstantAPINames.getEmployeeList.rawValue, body: request,
                               headers: ["X-Request-From": "tma"],
                               successHandler: successHandler, errorHandler: errorHandler, method: .post)

    }
}
