//
//  JobCardModels.swift
//  Enrich_TMA
//
//  Created by Harshal Patil on 11/11/19.
//  Copyright (c) 2019 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum JobCard {
    // MARK: Use cases

    enum BillOfMaterial {
        struct Request: Codable {
            let service_id: [String]
            let is_custom: Bool
        }

        struct Response: Codable {
            var status: Bool = false
            var message: String = ""
            let data: [Data]?
        }

        struct Data: Codable {
            let service_id: String?
            let bom_count: Int?
            let bom_list: [Bom_list]?
        }

        struct Bom_list: Codable {
            let bom_id: String?
            let bom_name: String?
            let bom_code: String?
            let created_at: String?
            let updated_at: String?
            let products: [Products]?
        }

        struct Products: Codable {
            let product_id: String?
            let product_name: String?
            let sku: String?
            let uom: String?
            let is_required: String?
            let qty: String?
        }
    }

    enum UpdateBillOfMaterial {
        struct Request: Codable {
            let update_service_status: String?
            let services: [Services]?
            let appointment_id: Int64?
            let full_appointment: Bool?
            let salon_code: String?
            let technician_name: String?
            let is_custom: Bool?
            let employee_id: String?
        }

        struct Services: Codable {
            let appointment_service_id: Int64?
            let products: [Products]?
        }

        struct Products: Codable {
            let product_code: String?
            let product_name: String?
            let quantity: String?
            let unit: String?
        }

        struct Response: Codable {
            var status: Bool = false
            var message: String = ""
        }
    }

    enum ChangeAppointmentStatus {
        struct Request: Codable {
            let status: String?
            let employee_id: String?
            let reason: String?
            let is_custom: Bool
        }

        struct Response: Codable {
            var status: Bool = false
            var message: String = ""
        }
    }

    enum ChangeServiceStatus {
        struct Request: Codable {
            let status: String?
            let is_custom: Bool
            let service_id: String?
            let appointment_id: String?
            let salon_code: String?
            let technician_name: String?
            let employee_id: String?
            let lat: Double?
            let long: Double?
        }

        struct Response: Codable {
            var status: Bool = false
            var message: String = ""
        }
    }

}
