//
//  ProductivityInteractor.swift
//  Enrich_TMA
//
//  Created by Harshal on 05/08/21.
//  Copyright (c) 2021 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProductivityBusinessLogic
{
  func doSomething(request: Productivity.Something.Request)
}

protocol ProductivityDataStore
{
  //var name: String { get set }
}

class ProductivityInteractor: ProductivityBusinessLogic, ProductivityDataStore
{
  var presenter: ProductivityPresentationLogic?
  var worker: ProductivityWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Productivity.Something.Request)
  {
    worker = ProductivityWorker()
    worker?.doSomeWork()
    
    let response = Productivity.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
