//
//  AddNewNoteWorker.swift
//  Enrich_SMA
//
//  Created by Harshal Patil on 13/01/20.
//  Copyright (c) 2020 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class AddNewNoteWorker {
    let networkLayer = NetworkLayerAlamofire() // Uncomment this in case do request using Alamofire for client request
    var presenter: AddNewNotePresentationLogic?

    func postRequestForAddClientNote(request: AddNewNote.ObserveNote.Request, method: HTTPMethod) {

        let errorHandler: (String) -> Void = { (error) in
            print(error)
            self.presenter?.presentError(responseError: error)
        }
        let successHandler: (ClientInformation.ClientNotes.Response) -> Void = { (response) in
            print(response)
            self.presenter?.presentAddClientNoteSuccess(response: response)
        }

        self.networkLayer.post(urlString: ConstantAPINames.addClientNote.rawValue, body: request, headers: [:], successHandler: successHandler, errorHandler: errorHandler, method: .post)

    }
}
