//
//  AddNewNoteInteractor.swift
//  Enrich_SMA
//
//  Created by Harshal Patil on 13/01/20.
//  Copyright (c) 2020 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol AddNewNoteBusinessLogic {
    func doPostNewClientNotes(request: AddNewNote.ObserveNote.Request, method: HTTPMethod)
}

class AddNewNoteInteractor: AddNewNoteBusinessLogic {
    var presenter: AddNewNotePresentationLogic?
    var worker: AddNewNoteWorker?
    //var name: String = ""

    // MARK: Do something

    func doPostNewClientNotes(request: AddNewNote.ObserveNote.Request, method: HTTPMethod) {
        worker = AddNewNoteWorker()
        worker?.presenter = self.presenter
        worker?.postRequestForAddClientNote(request: request, method: method)
    }
}
