//
//  TermsAndConditionsInteractor.swift
//  Enrich_TMA
//
//  Created by Harshal Patil on 22/11/19.
//  Copyright (c) 2019 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TermsAndConditionsBusinessLogic {
    func doGetTermsAndConditons(request: String, method: HTTPMethod)
}

protocol TermsAndConditionsDataStore {
    //var name: String { get set }
}

class TermsAndConditionsInteractor: TermsAndConditionsBusinessLogic, TermsAndConditionsDataStore {
    var presenter: TermsAndConditionsPresentationLogic?
    var worker: TermsAndConditionsWorker?

    // MARK: Do something

    func doGetTermsAndConditons(request: String, method: HTTPMethod) {
        worker = TermsAndConditionsWorker()
        worker?.presenter = self.presenter
        worker?.getRequestForTermsAndConditions(request: request, method: method)
    }
}
