//
//  TermsAndConditionsPresenter.swift
//  Enrich_TMA
//
//  Created by Harshal Patil on 22/11/19.
//  Copyright (c) 2019 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TermsAndConditionsPresentationLogic {
    func presentGetTermsAndConditionsSuccess<T: Decodable>(response: T)
    func presentGetTermsAndConditionsError(responseError: String?)
}

class TermsAndConditionsPresenter: TermsAndConditionsPresentationLogic {

    weak var viewController: TermsAndConditionsDisplayLogic?

    // MARK: Do something

    func presentGetTermsAndConditionsSuccess<T>(response: T) where T: Decodable {
        viewController?.displaySuccess(viewModel: response)
    }

    func presentGetTermsAndConditionsError(responseError: String?) {
        viewController?.displayError(errorMessage: responseError)
    }
}
