//
//  PackageFilterPresenter.swift
//  Enrich_TMA
//
//  Created by Harshal on 16/08/21.
//  Copyright (c) 2021 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PackageFilterPresentationLogic
{
  func presentSomething(response: PackageFilter.Something.Response)
}

class PackageFilterPresenter: PackageFilterPresentationLogic
{
  weak var viewController: PackageFilterDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: PackageFilter.Something.Response)
  {
    let viewModel = PackageFilter.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
