//
//  SearchByInteractor.swift
//  Enrich_TMA
//
//  Created by Harshal Patil on 25/10/19.
//  Copyright (c) 2019 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchByBusinessLogic
{
  func doSomething(request: SearchBy.Something.Request)
}

protocol SearchByDataStore
{
  //var name: String { get set }
}

class SearchByInteractor: SearchByBusinessLogic, SearchByDataStore
{
  var presenter: SearchByPresentationLogic?
  var worker: SearchByWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: SearchBy.Something.Request)
  {
    worker = SearchByWorker()
    worker?.doSomeWork()
    
    let response = SearchBy.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
