//
//  MyProfileInteractor.swift
//  Enrich_TMA
//
//  Created by Harshal Patil on 16/10/19.
//  Copyright (c) 2019 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MyProfileBusinessLogic
{
  func doSomething(request: MyProfile.Something.Request)
}

protocol MyProfileDataStore
{
  //var name: String { get set }
}

class MyProfileInteractor: MyProfileBusinessLogic, MyProfileDataStore
{
  var presenter: MyProfilePresentationLogic?
  var worker: MyProfileWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: MyProfile.Something.Request)
  {
    worker = MyProfileWorker()
    worker?.doSomeWork()
    
    let response = MyProfile.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
