//
//  ProductivityDetailsInteractor.swift
//  Enrich_TMA
//
//  Created by Harshal on 19/02/21.
//  Copyright (c) 2021 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProductivityDetailsBusinessLogic
{
  func doSomething(request: ProductivityDetails.Something.Request)
}

protocol ProductivityDetailsDataStore
{
  //var name: String { get set }
}

class ProductivityDetailsInteractor: ProductivityDetailsBusinessLogic, ProductivityDetailsDataStore
{
  var presenter: ProductivityDetailsPresentationLogic?
  var worker: ProductivityDetailsWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: ProductivityDetails.Something.Request)
  {
    worker = ProductivityDetailsWorker()
    worker?.doSomeWork()
    
    let response = ProductivityDetails.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
