//
//  ProductivityDetailsPresenter.swift
//  Enrich_TMA
//
//  Created by Harshal on 19/02/21.
//  Copyright (c) 2021 e-zest. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProductivityDetailsPresentationLogic
{
  func presentSomething(response: ProductivityDetails.Something.Response)
}

class ProductivityDetailsPresenter: ProductivityDetailsPresentationLogic
{
  weak var viewController: ProductivityDetailsDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: ProductivityDetails.Something.Response)
  {
    let viewModel = ProductivityDetails.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
